name: Makefile CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: create virtual env and install dependencies
      run: make venv

    - name: Test
      run: make test

    - name: Run
      run: make run

